### ISSUE TITLE
Update biomodels urls to https:/www.ebi.ac.uk/biomodels

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-org-website#15] opened 2021-02-09 20:51 UTC
This was opened on SBML discuss. See https://groups.google.com/d/msgid/sbml-discuss/9ff13b07-7254-4c4a-b071-ba9cc1171b61n%40googlegroups.com?utm_medium=email&utm_source=footer

> Hello SBML webmaster,
>
>The old BioModels, which the website URL was https//www.ebi.ac.uk/biomodels-main, had been retired since July 2020. Its replacement is since then https:/www.ebi.ac.uk/biomodels. We are kindly asking you to update all references of BioModels URL in SBML website so as to ensure BioModels services work well.
In particular, the online SBML validator does not work with providing a model via URL. We enforce to use https for all BioModels services.
Screenshot 2021-02-08 at 22.20.16.png
![image](https://user-images.githubusercontent.com/900538/107426757-eb8ddb00-6b20-11eb-9815-4be5482b36d9.png)

>
>It is grateful to have your cooperation.
>
>Best regards,
>Dr Tung Nguyen
>Senior Software Engineer
>Molecular Networks Team
>EMBL-EBI

**Comment by fbergmann** [comment] 2021-02-10 10:13
this has been resolved, ive deployed a new version of the validator. even though it was just an example. But maybe we should look for a shorter one, the current biomodels urls are really, really long.

**Comment by mhucka** [comment] 2022-01-06 03:14
Since the issue is resolved, I'm going to close this ticket.

**Closed** 2022-01-06 03:14 UTC
